networks:
  northwind-network:

volumes:
  northwind-db-vol:

services:
  northwind-db:
    image: stackupiss/northwind-db:v1
    platform: linux/amd64
    networks:
      - northwind-network
    volumes:
      - northwind-db-vol:/var/lib/mysql
  
  northwind-app:
    image: stackupiss/northwind-app:v1
    platform: linux/amd64
    environment:
      - DB_HOST=northwind-db
      - DB_USER=root
      - DB_PASSWORD=changeit
    networks:
      - northwind-network
    ports:
      - 8000-8100:3000
    depends_on:
      - northwind-db
